In [6]:
import pandas as pd
stats = pd.read_csv("../data/player_mvp_team_stats.csv", index_col=0)

In [7]:
stats

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,A.C. Green,PF,22,LAL,82,1,18.8,2.5,4.7,0.539,...,0.0,0.000,Los Angeles Lakers,62.0,20.0,0.756,0.0,117.3,109.5,6.84
1,Byron Scott,SG,24,LAL,76,62,28.8,6.7,13.0,0.513,...,0.0,0.000,Los Angeles Lakers,62.0,20.0,0.756,0.0,117.3,109.5,6.84
2,James Worthy,SF,24,LAL,75,73,32.7,8.4,14.5,0.579,...,780.0,0.009,Los Angeles Lakers,62.0,20.0,0.756,0.0,117.3,109.5,6.84
3,Jerome Henderson,C,26,LAL,1,0,3.0,2.0,3.0,0.667,...,0.0,0.000,Los Angeles Lakers,62.0,20.0,0.756,0.0,117.3,109.5,6.84
4,Kareem Abdul-Jabbar,C,38,LAL,79,79,33.3,9.6,16.9,0.564,...,780.0,0.173,Los Angeles Lakers,62.0,20.0,0.756,0.0,117.3,109.5,6.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17028,Spencer Hawes,PF,28,MIL,54,1,14.8,2.5,5.1,0.484,...,0.0,0.000,Milwaukee Bucks,42.0,40.0,0.512,9.0,103.6,103.8,-0.45
17029,Steve Novak,PF,33,MIL,8,0,2.8,0.3,0.9,0.286,...,0.0,0.000,Milwaukee Bucks,42.0,40.0,0.512,9.0,103.6,103.8,-0.45
17030,Terrence Jones,PF,25,MIL,54,12,23.5,4.3,9.1,0.470,...,0.0,0.000,Milwaukee Bucks,42.0,40.0,0.512,9.0,103.6,103.8,-0.45
17031,Thon Maker,C,19,MIL,57,34,9.9,1.5,3.2,0.459,...,0.0,0.000,Milwaukee Bucks,42.0,40.0,0.512,9.0,103.6,103.8,-0.45
17032,Tony Snell,SG,25,MIL,80,80,29.2,3.1,6.8,0.455,...,0.0,0.000,Milwaukee Bucks,42.0,40.0,0.512,9.0,103.6,103.8,-0.45

In [8]:
pd.isnull(stats).sum()

Player        0
Pos           0
Age           0
Tm            0
G             0
GS            0
MP            0
FG            0
FGA           0
FG%          63
3P            0
3PA           0
3P%        2499
2P            0
2PA           0
2P%         106
eFG%         63
FT            0
FTA           0
FT%         566
ORB           0
DRB           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
Year          0
Pts Won       0
Pts Max       0
Share         0
Team         42
W            42
L            42
W/L%         42
GB            0
PS/G         42
PA/G         42
SRS          42
dtype: int64

In [10]:
stats[pd.isnull(stats["3P%"])][["Player", "3PA"]]

                  Player  3PA
3       Jerome Henderson  0.0
5            Kurt Rambis  0.0
12     Pétur Guðmundsson  0.0
20           Kurt Rambis  0.0
23            Mike Smrek  0.0
...                  ...  ...
17002     Evan Eschmeyer  0.0
17003   Gheorghe Mureșan  0.0
17005      Jim McIlvaine  0.0
17011   Mark Hendrickson  0.0
17012       Michael Cage  0.0

[2499 rows x 2 columns]

In [20]:
stats[pd.isnull(stats["SRS"])][["Player", "GB"]]

                 Player   GB
12617       Bill Walton  0.0
12618      Billy Knight  0.0
12619    Billy McKinney  0.0
12620      Craig Hodges  0.0
12621       Dane Suttle  0.0
12622      Dave Robisch  0.0
12623       Derek Smith  0.0
12624          Don Buse  0.0
12625          Ed Nealy  0.0
12626       Greg Kelser  0.0
12627     Hank McDowell  0.0
12628       Hutch Jones  0.0
12629   James Donaldson  0.0
12630  Jerome Whitehead  0.0
12631   Joe Meriweather  0.0
12632       Kevin Loder  0.0
12633  LaSalle Thompson  0.0
12634        Larry Drew  0.0
12635    Larry Micheaux  0.0
12636     Linton Townes  0.0
12637    Mark Olberding  0.0
12638    Michael Brooks  0.0
12639      Mike Woodson  0.0
12640        Norm Nixon  0.0
12641      Reggie Theus  0.0
12642      Ricky Pierce  0.0
12643        Rory White  0.0
12644    Terry Cummings  0.0
16513       Dane Suttle  0.0
16514        David Pope  0.0
16515          Don Buse  0.0
16516          Ed Nealy  0.0
16517   Joe Meriweather  0.0
16518        Kenny Natt  0.0
16519  LaSalle Thompson  0.0
16520        Larry Drew  0.0
16521     Mark McNamara  0.0
16522    Mark Olberding  0.0
16523      Mike Woodson  0.0
16524       Otis Thorpe  0.0
16525    Pete Verhoeven  0.0
16526      Reggie Theus  0.0

In [19]:
stats[pd.isnull(stats["PS/G"])][["Player", "GB"]]

                 Player   GB
12617       Bill Walton  0.0
12618      Billy Knight  0.0
12619    Billy McKinney  0.0
12620      Craig Hodges  0.0
12621       Dane Suttle  0.0
12622      Dave Robisch  0.0
12623       Derek Smith  0.0
12624          Don Buse  0.0
12625          Ed Nealy  0.0
12626       Greg Kelser  0.0
12627     Hank McDowell  0.0
12628       Hutch Jones  0.0
12629   James Donaldson  0.0
12630  Jerome Whitehead  0.0
12631   Joe Meriweather  0.0
12632       Kevin Loder  0.0
12633  LaSalle Thompson  0.0
12634        Larry Drew  0.0
12635    Larry Micheaux  0.0
12636     Linton Townes  0.0
12637    Mark Olberding  0.0
12638    Michael Brooks  0.0
12639      Mike Woodson  0.0
12640        Norm Nixon  0.0
12641      Reggie Theus  0.0
12642      Ricky Pierce  0.0
12643        Rory White  0.0
12644    Terry Cummings  0.0
16513       Dane Suttle  0.0
16514        David Pope  0.0
16515          Don Buse  0.0
16516          Ed Nealy  0.0
16517   Joe Meriweather  0.0
16518        Kenny Natt  0.0
16519  LaSalle Thompson  0.0
16520        Larry Drew  0.0
16521     Mark McNamara  0.0
16522    Mark Olberding  0.0
16523      Mike Woodson  0.0
16524       Otis Thorpe  0.0
16525    Pete Verhoeven  0.0
16526      Reggie Theus  0.0

In [21]:
stats = stats.fillna(0)

In [23]:
stats.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
       'Pts Won', 'Pts Max', 'Share', 'Team', 'W', 'L', 'W/L%', 'GB', 'PS/G',
       'PA/G', 'SRS'],
      dtype='object')

In [24]:
predictors = ["Age", "G", "GS", "MP", "FG", "FGA", 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'W', 'L', 'W/L%',
       'GB', 'PS/G', 'PA/G', 'SRS']

In [25]:
train = stats[~(stats["Year"] == 2021)]
test = stats[stats["Year"] == 2021]

In [28]:
from sklearn.linear_model import Ridge
reg = Ridge(alpha=.1)

In [29]:
reg.fit(train[predictors],train["Share"])

Ridge(alpha=0.1)

In [30]:
predictions = reg.predict(test[predictors])
predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)

In [34]:
predictions

       predictions
697       0.015145
698      -0.011932
699       0.006662
700       0.003713
701       0.016046
...            ...
16827    -0.014842
16828    -0.007143
16829     0.017698
16830    -0.016149
16831    -0.003583

[540 rows x 1 columns]

In [31]:
combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)

In [32]:
combination.sort_values("Share", ascending=False).head(20)

                      Player  Share  predictions
708             Nikola Jokić  0.961     0.165439
10014            Joel Embiid  0.580     0.176647
4211           Stephen Curry  0.449     0.142722
11502  Giannis Antetokounmpo  0.345     0.205794
1566              Chris Paul  0.138     0.080791
13288            Luka Dončić  0.042     0.149602
8709          Damian Lillard  0.038     0.121127
4075           Julius Randle  0.020     0.094205
4070            Derrick Rose  0.010     0.037471
13710            Rudy Gobert  0.008     0.097337
4549       Russell Westbrook  0.005     0.122785
10006            Ben Simmons  0.003     0.069072
4877            James Harden  0.001     0.150844
6371           Kawhi Leonard  0.001     0.120596
4296            LeBron James  0.001     0.145566
11504            Jeff Teague  0.000    -0.003370
12896        Jalen McDaniels  0.000    -0.009567
12895           Grant Riller  0.000     0.000804
12894         Gordon Hayward  0.000     0.042914
12893        Devonte' Graham  0.000     0.013628

In [33]:
from sklearn.metrics import mean_squared_error
mean_squared_error(combination["Share"], combination["predictions"])

0.0026573461137736044

In [35]:
combination["Share"].value_counts()

# here 525 values have 0 share so this error metric is no good for us

Share
0.000    525
0.001      3
0.961      1
0.138      1
0.010      1
0.020      1
0.449      1
0.005      1
0.038      1
0.003      1
0.580      1
0.345      1
0.042      1
0.008      1
Name: count, dtype: int64

In [36]:
actual = combination.sort_values("Share", ascending=False)
predicted = combination.sort_values("predictions", ascending=False)
actual["Rk"] = list(range(1,actual.shape[0]+1))
predicted["Predicted_Rk"] = list(range(1,predicted.shape[0]+1))

In [37]:
actual.merge(predicted, on="Player").head(10)

,Player,Share_x,predictions_x,Rk,Share_y,predictions_y,Predicted_Rk
0,Nikola Jokić,0.961,0.165439,1,0.961,0.165439,3
1,Joel Embiid,0.580,0.176647,2,0.580,0.176647,2
2,Stephen Curry,0.449,0.142722,3,0.449,0.142722,8
3,Giannis Antetokounmpo,0.345,0.205794,4,0.345,0.205794,1
4,Chris Paul,0.138,0.080791,5,0.138,0.080791,29
5,Luka Dončić,0.042,0.149602,6,0.042,0.149602,5
6,Damian Lillard,0.038,0.121127,7,0.038,0.121127,12
7,Julius Randle,0.020,0.094205,8,0.020,0.094205,23
8,Derrick Rose,0.010,0.037471,9,0.010,0.037471,71
9,Rudy Gobert,0.008,0.097337,10,0.008,0.097337,19

In [38]:
def find_ap(combination):
    actual = combination.sort_values("Share", ascending=False).head(5)
    predicted = combination.sort_values("predictions", ascending=False)
    ps = []
    found = 0
    seen = 1
    for index,row in predicted.iterrows():
        if row["Player"] in actual["Player"].values:
            found += 1
            ps.append(found / seen)
        seen += 1

    return sum(ps) / len(ps)

In [40]:
ap = find_ap(combination)
ap

0.7344827586206897

In [41]:
years = list(range(1984,2023))

In [42]:
aps = []
all_predictions = []
for year in years[5:]:
    train = stats[stats["Year"] < year]
    test = stats[stats["Year"] == year]
    reg.fit(train[predictors],train["Share"])
    predictions = reg.predict(test[predictors])
    predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)
    combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)
    all_predictions.append(combination)
    aps.append(find_ap(combination))

In [43]:
sum(aps) / len(aps)

0.7708989669109502

In [44]:
def add_ranks(predictions):
    predictions = predictions.sort_values("predictions", ascending=False)
    predictions["Predicted_Rk"] = list(range(1,predictions.shape[0]+1))
    predictions = predictions.sort_values("Share", ascending=False)
    predictions["Rk"] = list(range(1,predictions.shape[0]+1))
    predictions["Diff"] = (predictions["Rk"] - predictions["Predicted_Rk"])
    return predictions

In [49]:
ranking = add_ranks(all_predictions[28])
ranking[ranking['Rk'] < 6].sort_values('Diff', ascending = False)

                  Player  Share  predictions  Predicted_Rk  Rk  Diff
7460   Russell Westbrook  0.879     0.208532             1   1     0
13323       James Harden  0.746     0.194770             2   2     0
7863        LeBron James  0.330     0.178729             4   4     0
2929       Isaiah Thomas  0.080     0.133251             9   5    -4
15037      Kawhi Leonard  0.495     0.139052             8   3    -5

In [50]:
def backtest(stats, model, years, predictors):
    aps = []
    all_predictions = []
    for year in years:
        train = stats[stats["Year"] < year]
        test = stats[stats["Year"] == year]
        model.fit(train[predictors],train["Share"])
        predictions = model.predict(test[predictors])
        predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)
        combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)
        combination = add_ranks(combination)
        all_predictions.append(combination)
        aps.append(find_ap(combination))
    return sum(aps) / len(aps), aps, pd.concat(all_predictions)

In [51]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[5:], predictors)

In [53]:
mean_ap

0.7708989669109502

In [54]:
all_predictions[all_predictions["Rk"] < 5].sort_values("Diff").head(10)

                Player  Share  predictions  Predicted_Rk  Rk  Diff
6218        Steve Nash  0.839     0.054543            31   1   -30
1401        Jason Kidd  0.712     0.054505            26   2   -24
6236        Steve Nash  0.739     0.070886            23   1   -22
15448      Joakim Noah  0.258     0.055045            26   4   -22
9892   Peja Stojaković  0.228     0.052073            21   4   -17
974       Devin Booker  0.216     0.097342            18   4   -14
1066     Allen Iverson  0.270     0.024030            18   4   -14
6251        Steve Nash  0.785     0.087458            15   2   -13
5483      Tim Hardaway  0.207     0.074791            16   4   -12
7904       Kobe Bryant  0.291     0.082563            15   4   -11

In [55]:
pd.concat([pd.Series(reg.coef_), pd.Series(predictors)], axis=1).sort_values(0, ascending=False)

           0     1
28  0.131406  W/L%
13  0.065271  eFG%
18  0.028404   DRB
10  0.025637    2P
17  0.015775   ORB
21  0.014560   STL
7   0.010695    3P
22  0.010573   BLK
25  0.010057   PTS
20  0.008034   AST
5   0.005776   FGA
15  0.005083   FTA
12  0.001765   2P%
29  0.000361    GB
27  0.000300     L
0   0.000263   Age
1   0.000101     G
2  -0.000022    GS
30 -0.000236  PS/G
26 -0.000344     W
31 -0.000476  PA/G
32 -0.001262   SRS
24 -0.002430    PF
14 -0.002473    FT
3  -0.004311    MP
16 -0.007151   FT%
9  -0.008621   3P%
23 -0.009840   TOV
8  -0.011642   3PA
4  -0.012645    FG
11 -0.017268   2PA
19 -0.020259   TRB
6  -0.127920   FG%

In [81]:
stat_ratios = stats.groupby('Year')[["PTS", "AST", "STL", "BLK", "3P", "Year"]].apply(lambda x: x.sort_values(by = 'Year', ascending=False)/x.mean())
stat_ratios = stat_ratios.droplevel(0)

In [86]:
stat_ratios

            PTS       AST       STL       BLK        3P  Year
2329   3.319760  1.750510  1.090265  0.223027  0.000000   1.0
12618  1.388658  0.942582  0.953982  0.223027  2.053333   1.0
12625  0.271222  0.314194  0.817699  0.223027  0.000000   1.0
12624  0.542445  1.795395  1.499115  0.000000  4.106667   1.0
12623  1.063191  0.583503  0.681416  0.892107  0.000000   1.0
...         ...       ...       ...       ...       ...   ...
4312   0.461165  0.214102  0.659221  0.541387  0.764578   1.0
4313   0.230583  0.000000  0.164805  0.270694  0.109225   1.0
4314   0.485437  0.267628  0.329610  0.270694  0.983029   1.0
4315   2.135922  1.712820  1.648052  2.706935  1.529157   1.0
14427  0.000000  0.000000  0.000000  0.000000  0.000000   1.0

[17033 rows x 6 columns]

In [82]:
#stats[["PTS_R", "AST_R", "STL_R", "BLK_R", "3P_R"]] = stat_ratios[["PTS", "AST", "STL", "BLK", "3P"]]
#stat_ratios
stats[["PTS_R", "AST_R", "STL_R", "BLK_R", "3P_R"]] = stat_ratios[["PTS", "AST", "STL", "BLK", "3P"]]

In [88]:
stats[stats['Player'] == 'A.C. Green']

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,W/L%,GB,PS/G,PA/G,SRS,PTS_R,AST_R,STL_R,BLK_R,3P_R
0,A.C. Green,PF,22,LAL,82,1,18.8,2.5,4.7,0.539,...,0.756,0.0,117.3,109.5,6.84,0.674727,0.313068,0.778905,1.341719,0.000000
14,A.C. Green,PF,23,LAL,79,72,28.4,4.0,7.4,0.538,...,0.793,0.0,117.8,108.5,8.32,1.172077,0.501506,1.211888,2.187911,0.000000
26,A.C. Green,PF,24,LAL,82,64,32.1,3.9,7.8,0.503,...,0.756,0.0,112.8,107.0,4.81,1.246645,0.504657,1.484663,1.108871,0.000000
41,A.C. Green,PF,25,LAL,82,82,30.6,4.9,9.2,0.529,...,0.695,0.0,114.7,107.5,6.38,1.458844,0.600553,1.422099,1.588235,0.000000
53,A.C. Green,PF,26,LAL,82,82,33.0,4.7,9.8,0.478,...,0.768,0.0,110.7,103.9,6.74,1.446394,0.524403,1.101744,1.430189,1.129657
67,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,0.476,...,0.707,5.0,106.3,99.6,6.73,1.013334,0.420714,0.961127,0.673469,0.508587
79,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,0.476,...,0.524,14.0,100.4,101.5,-0.95,1.534567,0.678383,1.500353,0.853510,0.456805
94,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,0.537,...,0.476,23.0,104.2,105.5,-1.20,1.432507,0.673326,1.500525,1.127820,0.806618
107,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,0.502,...,0.683,7.0,108.2,103.4,4.68,1.770767,0.851797,1.234513,1.131387,0.376284
122,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,0.504,...,0.720,0.0,110.6,106.8,3.86,1.319103,0.758048,0.991605,0.931570,1.107162
137,A.C. Green,SF,32,PHO,82,36,25.8,2.6,5.4,0.484,...,0.500,23.0,104.3,104.0,0.28,0.889320,0.466739,0.723462,0.697826,0.402634
152,A.C. Green,PF,33,DAL,83,73,30.0,2.8,5.8,0.483,...,0.293,40.0,90.6,97.0,-6.47,0.896924,0.439243,1.136598,0.472416,0.000000
169,A.C. Green,PF,34,DAL,82,68,32.3,3.0,6.5,0.453,...,0.244,42.0,91.4,97.5,-6.33,0.918463,0.824362,1.394536,0.708445,0.000000
185,A.C. Green,PF,35,DAL,50,35,18.5,2.2,5.1,0.422,...,0.380,18.0,91.6,94.0,-2.50,0.667203,0.302863,0.888889,0.498584,0.000000
199,A.C. Green,PF,36,LAL,82,82,23.5,2.1,4.7,0.447,...,0.817,0.0,100.8,92.3,8.41,0.627089,0.540640,0.894701,0.467519,0.000000
213,A.C. Green,PF,37,MIA,82,1,17.2,1.8,4.0,0.444,...,0.610,6.0,88.9,86.6,1.73,0.576052,0.274186,0.596349,0.228025,0.000000

In [89]:
predictors += ["PTS_R", "AST_R", "STL_R", "BLK_R", "3P_R"]

In [102]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[5:], predictors)

In [103]:
mean_ap

0.7684920625124816

In [108]:
stats["NPos"] = stats["Pos"].astype("category").cat.codes
stats["NTm"] = stats["Tm"].astype("category").cat.codes

In [139]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators=50, random_state=1, min_samples_split=5)

In [141]:
mean_ap, aps, all_predictions = backtest(stats, rf, years[25:], predictors + ["NPos", "NTm"])
mean_ap

0.7818343561200705

In [129]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[25:], predictors)
mean_ap

0.7931116318000554

2022